#!/bin/sh

javac -d out/production/CraftingInterpreters/ src/com/craftinginterpreters/tool/GenerateAst.java 
pushd out/production/CraftingInterpreters
java com.craftinginterpreters.tool.GenerateAst ../../../src/com/craftinginterpreters/lox
popd